### ISSUE TITLE
figure out date stuff

### ISSUE THREAD

**Issue by aaronj1335** [austinjavascript/austinjavascript.github.io#11]
apparently jekyll builds run in a timezone so different than austin's that [dates](https://github.com/austinjavascript/austinjavascript.github.io/blob/7077dd2204a8d8422d36634377c8de3c1035a1a7/index.html#L9) might show up as a different day.  oops.

a couple options:
- just render the date and have some JS come back and fix it up
  - what do we render until the date shows up? probably doesn't matter that much.
- use [custom elements](https://github.com/github/time-elements)!
  - seems really heavyweight for what we need tho...

**Comment by lawnsea** [comment]
> what do we render until the date shows up? probably doesn't matter that much.

i mean, if they are browsing with js turned off we don't want them to come anyway, right?

**Comment by aaronj1335** [comment]
whoa good call. they'd probably show up in a railsconf tee or some crap.

@cowboyd :eyes:

**Comment by cowboyd** [comment]
Alls I can say is that if TxJS OR RxJS had bothered to print T-shirts, we wouldn't have this problem, now would we?

**Comment by aaronj1335** [comment]
oh hey RxJS i'm actually a big fan of that library

**Comment by cowboyd** [comment]
I heard somewhere that it handles dates and timezones pretty good.

**Comment by lawnsea** [comment]
lol

oh hey, on that note, @aaronj1335, the walgreens at 2222/burnet says they're hiring PT Rx techs. want me to drop off a resume for ya?

**Comment by aaronj1335** [comment]
yes. you've still got my pre-waterfall resume, right? nothings really changed since then.

**Comment by lawnsea** [comment]
:zap:

**Comment by aaronj1335** [comment]
closed by c4e5035.

it increases the number of requests from 7 to 8, and increases page weight from 9.1kb to 15.6kb. uncached page loads went from ~197ms on a fast connection to 229ms.

now cached page loads? don't worry about cached page loads.

**Comment by lawnsea** [comment]
:fireworks:
