### ISSUE TITLE
We turned down Joe and Slex too far

### ISSUE THREAD

**Issue by lawnsea** [austinjavascript/austinjavascript.github.io#15]
...and for what?

I don't see them at all on http://austinjavascript.com/about/

**Comment by aaronj1335** [comment]
oops

**Comment by aaronj1335** [comment]
closed by 68fc165

**Comment by aaronj1335** [comment]
just ftr i sincerely appreciate the lil john reference there. he's the joe cocker of this generation.

**Comment by lawnsea** [comment]
lol :gem:
