### ISSUE TITLE
august 18th meetup

### ISSUE THREAD

**Issue by aaronj1335** [austinjavascript/austinjavascript.github.io#19]
- [X] invoice to sponsor (thnx @lawnsea)
- [ ] money from sponsor
- [X] venue (thnx @beaktor and @tgrochowicz)
- [ ] blog post (me)
- [x] speaker (thnx @iheanyi)

**Comment by iheanyi** [comment]
Time is at 7:30pm, right @aaronj1335 @lawnsea ?

**Comment by aaronj1335** [comment]
ya
