### ISSUE TITLE
November meetup

### ISSUE THREAD

**Issue by aaronj1335** [austinjavascript/austinjavascript.github.io#38]
- [x] speaker: @jonloyens 
- [ ] sponsor
- [ ] confirm location with @AndyCouch
- [ ] blog post

**Comment by jonloyens** [comment]
Hey @aaronj1335 - do you want a summary of my talk for the site?  I'm psyched.

**Comment by lawnsea** [comment]
@jonloyens a talk description would be very helpful, thanks.
