### ISSUE TITLE
February meetup

### ISSUE THREAD

**Issue by aaronj1335** [austinjavascript/austinjavascript.github.io#41]
February 21<sup>st</sup>.

- [x] Speaker: @astashov on [Immutable.js](https://facebook.github.io/immutable-js/)?
- [ ] Sponsor:
- [ ] Venue: will confirm early February

**Comment by astashov** [comment]
I'd prefer after February, in January on February I may have to go to California for a holiday party, the dates are tentative so far, so I don't want to accidentally them overlap with the meetup dates.

**Comment by aaronj1335** [comment]
Ah, right on, in that case @markedwardsims would you be willing to speak February 21<sup>st</sup> instead of April?

**Comment by markedwardsims** [comment]
I'd love to, but I'll be on a family vacation that week. Let me double check to make certain.

**Comment by astashov** [comment]
Okay, so the holiday party gonna be on Jan, 27, so I can make it with the talk in Feb, if you are still interested :)

**Comment by aaronj1335** [comment]
Perfect, thanks Anton, we'll lock you in for Feb!
