### ISSUE TITLE
HTTPS is a thing

### ISSUE THREAD

**Issue by lawnsea** [austinjavascript/austinjavascript.github.io#55]
We should do the thing that @knksmith57 told me about that lets us serve this site from austinjavascript.com over HTTPS.

**Comment by aaronj1335** [comment]
Cloudflare works really well with gh pages, and they sponsored! We'll just need @joemccann to point DNS to it.

**Comment by aaronj1335** [comment]
closed with 87b931b0ff8ea1c82d29a480c1c932bad8818718
