### ISSUE TITLE
January 2019 Meetup

### ISSUE THREAD

**Issue by seejamescode** [austinjavascript/austinjavascript.github.io#80]
- [x] Speaker
- [X] Sponsor (@magento)
- [x] Confirm venue
- [X] Meetup post
- [X] Blog post
- [X] Tweet
- [X] Order pizza
- [ ] Record stats
- [ ] Invoice sponsor

**Comment by seejamescode** [comment]
Hi everyone! I talked to @lawnsea about speaking and he said to leave an abstract and bio here:

---

**Saving CSS Grid Headaches with JavaScript**

Grid frameworks in CSS help keep a product, department, or even a whole company visually aligned. However, they can be a struggle to maintain while satisfying different experiences’ needs. Thankfully, scripting languages have a knack for keeping everything sane. By creating a new open-source package that generates grid frameworks, we will cover:

- Abstracting design specs for reusable code
- Performance vs CSS browser support
- The flexibility of isomorphic JavaScript packages

**About James Y Rauhut**

James is a front-end dev and UX designer that loves fusing both roles. He enjoys talking about design systems, progressive web apps, and that horrid CSS-in-JS. Serious contributions to the web dev community include CSS Gridish and Create React App DevOps. Not-so-serious contributions include https://IsTexasBackYet.com. Follow him on Twitter or Medium at @seejamescode!

**Comment by seejamescode** [comment]
Hey @lawnsea, any chance for a future month if November isn’t working out?

**Comment by lawnsea** [comment]
hey @seejamescode, let's bump this to january. my wife wants us to drive up to dallas on tuesday, so i think that will be easier.

**Comment by lawnsea** [comment]
if january doesn't work for you, we have february available as well

**Comment by seejamescode** [comment]
![image](https://user-images.githubusercontent.com/7519029/48424972-75c01c80-e729-11e8-996e-26d73b039df5.png)

**Comment by seejamescode** [comment]
Hey @lawnsea, is this still happening or do we need to move it back?

**Comment by DrewML** [comment]
Hey @seejamescode! @lawnsea has to miss the January meetup, but we're on with Spredfast as the venue, and I'll be coordinating.

Either myself or @lawnsea will get the blog post up shortly so it can be shared around social. Thanks for writing up a solid abstract ✌️

**Comment by lawnsea** [comment]
@seejamescode we're down if you are! We're working out sponsor details right now. I'll get a blog post started.

**Comment by seejamescode** [comment]
Sounds great!

**Comment by seejamescode** [comment]
Hey @DrewML, what time should I show up to get all set up? And will there be a display connection for USB-C?

**Comment by DrewML** [comment]
Sorry for the delay @seejamescode! PR open for blog post in #82.

I'd recommend showing up around 7:00PM. That's roughly around the time that @beaktor starts prepping the room. There should be an adapter on the premises

**Comment by seejamescode** [comment]
Hey y’all, just a heads up that the blog post lists the start time at 6:30pm.

**Comment by beaktor** [comment]
@seejamescode thanks for catching that! I've updated the post and the change should be reflected shortly :+1:

**Comment by DrewML** [comment]
Pizza order placed at 3:10pm withEast Side Pies Rosewood (512) 524-0933:
2 pepperoni
1 pepperoni and mushroom
1 margherita
1 spinach, mushroom, green bell pepper, black olive, and basil

all double cut
plates and napkins for 50
deliver at 7:15pm to 200 W Cesar Chavez St #300 (3rd floor)

**Comment by beaktor** [comment]
pepmush my favorite

![image](https://user-images.githubusercontent.com/5374614/51212258-9b120800-18dd-11e9-9d0a-405206bba283.png)

**Comment by DrewML** [comment]
Inventory:

- 32 beers left out of ~50
- 1 Whole pepp pizza left
- 1/4 Marg pizza left
